### ISSUE TITLE
Cannot load pretrained model

### ISSUE THREAD

**Issue by pmwenzel** [lvzhaoyang/DeeperInverseCompositionalAlgorithm#2]
It seems that I cannot load a pre-trained model with the code. I have used the anaconda from the repo. I guess the problem is the CUDA version. I use CUDA 10.0, however, your requirements say CUDA > 9.0. Did you also test with a newer version? Thanks a lot

` net.load_state_dict(torch.load(config.checkpoint)['state_dict'])
  File "/home/anaconda3/envs/deepICN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for LeastSquareTracking:
	Missing key(s) in state_dict: "encoder.net0.0........`

**Comment by lvzhaoyang** [comment]
I did at some time with cuda 10.0 with no issue. Did you change the conda environment?

**Comment by pmwenzel** [comment]
No, I didn't. However, I guess this requirement anyway won't work if you use it when you only have cuda 10.0.

- pytorch=1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1

**Comment by lvzhaoyang** [comment]
Maybe, can you give it a try to install the pytorch 1.0 with cuda 10.0, and let me know how it goes?

**Comment by pmwenzel** [comment]
I have finally found the issue. It is not the pytorch version, but it is the logger function save_checkpoint. It checks if the number of GPUs is greater than 1, and saves the state dict differently. It still saves it that way even if you only train with 1 out of N GPUs.
