### ISSUE TITLE
Question about inverse_update_pose function

### ISSUE THREAD

**Issue by zacjiang** [lvzhaoyang/DeeperInverseCompositionalAlgorithm#3]
Thanks for the great work. I have a question related to the pose update:
In models/algorithms.py, in the function 
def inverse_update_pose(H, Rhs, pose):
...
pose = geometry.batch_Rt_compose(R, t, d_R, d_t)
...
However, in models/geometry.py, batch_Rt_compose was defined as
def batch_Rt_compose(d_R, d_t, R0, t0):

Could you please advise on how the update was performed? Thanks a lot.

**Comment by lvzhaoyang** [comment]
In the paper, we define the multiplication as *right-multiplication*. This is what you see here

https://github.com/lvzhaoyang/DeeperInverseCompositionalAlgorithm/blob/638f3e538944170dfb9edd6994ef03e9debf6e3d/code/models/algorithms.py#L464

The interface we defined is *left-multiplication*, which you see in the comment. 
https://github.com/lvzhaoyang/DeeperInverseCompositionalAlgorithm/blob/638f3e538944170dfb9edd6994ef03e9debf6e3d/code/models/geometry.py#L100

This is why you see the order is reversed. Sorry that the naming causes your confusion. I will consider to update it.

**Comment by zacjiang** [comment]
Thanks Zhaoyang.
