### ISSUE TITLE
What is the loss of 2D Affine Motion Estimation? Answer: diff between predicted and truth motion

### ISSUE THREAD

**Issue by xmyqsh** [lvzhaoyang/DeeperInverseCompositionalAlgorithm#6]
It seems that the implementation of 2D Affine Motion Estimation is not released.
And the 2D loss is not given.

Can I use photometric loss or feature metric loss in an unsupervised way for 2D Motion Estimation?

Is the algorithm robust for noisy depth data, eg. the depth is predicted, no ground truth.

How about learning depth together with motion?

**Comment by xmyqsh** [comment]
Answer: diff between predicted and truth motion, **also, it is 2d Affine Motion, not 3D motion**,
**3D motion must be together with depth or depth prediction**

It seems that all optimization-based motion estimation methods are supervised learning.
Because it optimizes the pose directly and iteratively, eg. IC-STN, DEEPV2D.
Can we set the last iterative error `delta_efslu` to be zero as the unsupervised learning metric?
Also, an additional photometric loss or feature metric loss based on the last iterative residual `r` could also be added.

**Comment by xmyqsh** [comment]
Awesome repo and paper!
It is not a research, it is a lecture!

**Comment by lvzhaoyang** [comment]
I did not release the 2D affine transform, which should be straight-forward to implement according to the supplementary if there is a need. I tried to make this repo as concise as possible. I am glad it helps you. 

I would not say direct supervision is necessary, but empirically I would say it ensures there is no ambiguity in the optimization. If you have tried to train yourself, you may find it is not that easy to train the unrolled optimization.  How to make it faster to train, have better convergence, and use self-supervision are all interesting open research questions. I would like to know more if you have some findings in these.
